### ISSUE TITLE
Detect incompatibility and raise a relevant exception

### ISSUE THREAD

**Issue by sorsaffari** [vaticle/typedb-client-java#25]
## Problem to Solve

When there is an incompatibility between Client Java and the running Grakn Server, the exception thrown by the client seems unrelated to the real cause of the problem. In fact, the error message may even be incorrect, given that the keyspace does exist with the given name.

## Current Workaround

If encountering this exception for the first time, only searching the web or asking the community can lead the user to the solution.

## Proposed Solution

Have Client Java to identify the incompatibility and throw an exception with a helpful message. e.g. `Client Java version 1.5.3 does not support the running Grakn Core server. Please refer to the documentation of client Java to ensure compatibility.`

## Additional Information

N/A

**Comment by alexjpwalker** [comment]
This issue is still relevant in 2.0.

**Comment by alexjpwalker** [comment]
The discussion from https://github.com/graknlabs/client-nodejs/issues/47 may be of relevance here.

**Comment by alexjpwalker** [comment]
To summarise:

- Server should expose an RPC endpoint to describe its version number
- Protocol for this endpoint should remain stable permanently* to preserve backwards compatibility
- The client can then detect incompatibility and raise a relevant exception

We should also consider:
- Declaring the product name (TypeDB or TypeDB Cluster) in the response
- Exposing this endpoint as a client feature that a user can call manually to get basic server info

**Comment by alexjpwalker** [comment]
https://github.com/vaticle/typedb-studio/issues/567

**Comment by flyingsilverfin** [comment]
Implemented in #421
