### ISSUE TITLE
test-deployment-maven fails when the protocol version is a snapshot

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-client-java#322]
## Problem to Solve

test-deployment-maven fails when the protocol version is a snapshot, because it tries to pull from the release repository.

**Comment by haikalpribadi** [comment]
I this issue still valid, @alexjpwalker ? Looks like commits are all green on `master` now, and they all run `test-deployment-maven`.

**Comment by alexjpwalker** [comment]
Interesting, I just checked the logs of one of the successful commits, and it appears to now _try_ to download Protocol from the Release repo, fail silently, and then successfully grab it from the Snapshot repo:

https://grabl.io/vaticle/typedb-client-java/9291efb0afabbe8950aa2c56f8a68598781e315c/build/1/correctness/1/test-deployment-maven/1/command.log

```
Downloading from repo.vaticle.com.release: https://repo.vaticle.com/repository/maven/com/vaticle/typedb/typedb-protocol/d608bb39f21013ed0e569581b599900d1d60ede2/typedb-protocol-d608bb39f21013ed0e569581b599900d1d60ede2.pom
Downloading from repo.vaticle.com.snapshot: https://repo.vaticle.com/repository/maven-snapshot/com/vaticle/typedb/typedb-protocol/d608bb39f21013ed0e569581b599900d1d60ede2/typedb-protocol-d608bb39f21013ed0e569581b599900d1d60ede2.pom
Progress (1): 3.5 kB
                    
Downloaded from repo.vaticle.com.snapshot: https://repo.vaticle.com/repository/maven-snapshot/com/vaticle/typedb/typedb-protocol/d608bb39f21013ed0e569581b599900d1d60ede2/typedb-protocol-d608bb39f21013ed0e569581b599900d1d60ede2.pom (3.5 kB at 11 kB/s)
```
Well, one way or another, it works, so I guess we can close this.
