### ISSUE TITLE
Cluster BDD Scenarios uses Core client and options

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-client-java#336]
Cluster BDD Scenarios are using Core client and options. This is incorrect and should be fixed.

Please see the following non-exhaustive examples:

- https://github.com/vaticle/typedb-client-java/blob/master/test/behaviour/connection/ConnectionStepsCluster.java#L61
- https://github.com/vaticle/typedb-client-java/blob/master/test/behaviour/connection/transaction/TransactionSteps.java#L71

**Comment by alexjpwalker** [comment]
Looking at the referenced lines, this bug appears to have been fixed.

That is in line with my expectations too - the tests could not possibly pass if we were using a Core client and Core options.
