### ISSUE TITLE
[Java Client]: query.withTx(writeTransaction).execute() returns empty list when type mismatch

### ISSUE THREAD

**Issue by Irtazaraza** [vaticle/typedb-client-java#49]
SCHEMA: 

define 
person sub entity,
  has person-id,
  plays employee;

company sub entity,
  has name,
  plays employer;

employment sub relationship,
  relates employee,
  relates employer;

person-id sub attribute datatype double;
name sub attribute datatype string;

JAVA CLIENT:

InsertQuery insertQuery = Graql.match(
                        var("p").isa("person").has("person-id", "1"),
                        var("c").isa("company").has("name", "grakn"))
                        .insert(var("e").isa("employment").rel("employer", "c").rel("employee", "p"));

Grakn.Transaction writeTransaction = session.transaction(GraknTxType.WRITE);

List<ConceptMap> insertedId = insertQuery.withTx(writeTransaction).execute(); 

**=> RETURNS an EMPTY LIST; but should return an error saying attribute type person-id is of datatype double.**

**Comment by alexjpwalker** [comment]
This bug was actually fixed by the addition of server-side schema validation, albeit not in a pretty way. The query now returns the following error:
```
[QRY16] Invalid Query Pattern: The pattern '{{ $p isa person; $p has $_0; 
$_1 isa name; $_1 = "grakn"; 
$c has $_1; $c isa company; 
$_0 = "1"; $_0 isa person-id; }}' is illegal in the current schema.
```
I've raised:
- https://github.com/vaticle/typedb/issues/6727
- https://github.com/vaticle/typedb/issues/6728

We can now close this issue.
